[build]
  command = "npm install --legacy-peer-deps && npm run build:web"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 